name: Update Version

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Bump Version
        uses: michmich112/version-bumper@master
        with:
          options-file: ".github/workflows/version.conf.json"
          github-token: ${{ secrets.GITHUB_TOKEN }}
